
<div class="col-sm-8 right-container">
    
    <div class="row">
        
        <div class="col-sm-2">
            <a class="btn btn-default" href="<?php echo $this->url(array(), 'log'); ?>">Admin log</a>
        </div>
        
        <div class="col-sm-2">
            <a class="btn btn-default" href="<?php echo $this->url(array(), 'log-frontend'); ?>">Frontend log</a>
        </div>
        
    </div>


</div>



