
<div class="row">
    <div class="col-sm-2" style="margin-bottom: 20px;">
        <a class="btn btn-default" href="<?php echo $this->url(array(), 'log-clear-frontend'); ?>">Wyczyść log</a>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div>
            <pre class="reports-container">
                    <?php echo $this->log; ?>
            </pre>
        </div>
    </div>
</div>