

    <div class="row">

        <div class="col-sm-12">

            <!-- Zakładki -->
            <ul class="nav nav-pills nav-justified" role="tablist">
                <li class="active"><a href="#1przyciskjust" role="tab" data-toggle="tab">1 przycisk</a></li>
                <li><a href="#2przyciskjust" role="tab" data-toggle="tab">2 przycisk</a></li>
                <li><a href="#3przyciskjust" role="tab" data-toggle="tab">3 przycisk</a></li>
                <li><a href="#4przyciskjust" role="tab" data-toggle="tab">4 przycisk</a></li>
            </ul>

        </div>

    </div>


    <div class="row">

        <div class="col-sm-12">

            <!-- Zawartość zakładek -->
            <div class="tab-content">
                <div class="tab-pane active" id="1przycisk">Zawartość pierwszego przycisku</div>
                <div class="tab-pane" id="2przyciskjust">Zawartość drugiego przycisku</div>
                <div class="tab-pane" id="3przyciskjust">Zawartość trzeciego przycisku</div>
                <div class="tab-pane" id="4przyciskjust">Zawartość czwartego przycisku</div>
            </div>

        </div>

    </div>





