<?php
$uri = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
$exploded = explode('/', $uri);
$class = '';

if(in_array($exploded[1], $this->marker)){
    $style = 'style="background:#ccccff;"';
} else {
    $style = '';
}

?>



<div class="panel panel-default" <?php echo $style; ?>>

    <div class="panel-heading" style="color: #ffccff">

        <h3 class="panel-title">
            <span class="badge"><?php echo $this->n; ?></span>
            <a href="<?php echo $this->url(array(), trim($this->route, '/')); ?>"><?php echo $this->title; ?></a>
        </h3>
    </div>

    <div class="panel-body">

        <?php if (!empty($this->content)): ?>

            <?php foreach ($this->content as $key => $val): ?>

                <a style="width: 100%; margin-bottom: 5px;" class="btn btn-info" href="<?php echo $this->url(array(), trim($val->route, '/')); ?>"><?php echo $val->title ?></a>

            <?php endforeach; ?>

        <?php endif; ?>

    </div>





</div>


