
<?php
$value = basename($this->value);
?>

<div class="form-group">
    <div class="iframe-wrapper"> 
        <iframe scroll="auto" seamless="seamless" id="image-process-iframe" width="100%" height="800" frameborder="0" marginwidth="15" src="<?php echo $this->url(array('img-name' => $value), 'images'); ?>">
        <p>Your browser does not support iframes.</p>
        </iframe>
    </div>
    <input type="hidden" name="image-input" value="" id="image-input" />
</div>

