

<?php if ($this->pageCount): ?>


    <div>
        <!-- First page link /articles/index/page/<?php //echo $this->first; ?> -->
        <?php if (isset($this->previous)): ?>
            <a prop="pagin" class="btn btn-primary" href="<?php echo $this->url(array('page' => $this->first), 'articles'); ?>">
                <i class="fa fa-caret-square-o-left"></i>
                <i class="fa fa-caret-square-o-left"></i>
            </a>
        <?php endif; ?>


        <!-- end First page link -->

        <!-- Previous page link /articles/index/page/<?php //echo $this->previous; ?>-->
        <?php if (isset($this->previous)): ?>
            <a prop="pagin" class="btn btn-primary" href="<?php echo $this->url(array('page' => $this->previous), 'articles'); ?>">
                <i class="fa fa-caret-square-o-left"></i>
            </a>
        <?php endif; ?>

        <!--/articles/index/page/<?php //echo $page; ?>-->
        <span>
            <?php foreach ($this->pagesInRange as $page): ?>

                <?php if ($page == $this->current): ?>
                    <a class="btn btn-danger"><?php echo $page; ?></a>
                <?php else: ?>
                    <a prop="pagin" class="btn btn-info btn-sm" href="<?php echo $this->url(array('page' => $page), 'articles'); ?>"><?php echo $page; ?></a>

                <?php endif; ?>
            <?php endforeach; ?>
        </span>

        <!-- Next page link /articles/index/page/<?php //echo $this->next; ?>-->
        <?php if (isset($this->next)): ?>
            <a prop="pagin" class="btn btn-primary" href="<?php echo $this->url(array('page' => $this->next), 'articles'); ?>">
                <i class="fa fa-caret-square-o-right"></i>
            </a>
        <?php endif; ?>


        <!-- Last page link /articles/index/page/<?php //echo $this->last; ?>-->
        <?php if (isset($this->next)): ?>
            <a prop="pagin" class="btn btn-primary" href="<?php echo $this->url(array('page' => $this->last), 'articles'); ?>">
                <i class="fa fa-caret-square-o-right"></i>
                <i class="fa fa-caret-square-o-right"></i>
            </a>
        <?php endif; ?>

    </div>
<?php endif; ?>


