

<?php if ($this->pageCount): ?>


    <div>
        
        <?php if (isset($this->previous)): ?>
            <a prop="pagin" class="btn btn-primary" href="<?php echo $this->url(array('page' => $this->first), 'comments'); ?>">
                <i class="fa fa-caret-square-o-left"></i>
                <i class="fa fa-caret-square-o-left"></i>
            </a>
        <?php endif; ?>

        <?php if (isset($this->previous)): ?>
            <a prop="pagin" class="btn btn-primary" href="<?php echo $this->url(array('page' => $this->previous), 'comments'); ?>">
                <i class="fa fa-caret-square-o-left"></i>
            </a>
        <?php endif; ?>

        <span>
            <?php foreach ($this->pagesInRange as $page): ?>

                <?php if ($page == $this->current): ?>
                    <a class="btn btn-danger"><?php echo $page; ?></a>
                <?php else: ?>
                    <a prop="pagin" class="btn btn-info btn-sm" href="<?php echo $this->url(array('page' => $page), 'comments'); ?>"><?php echo $page; ?></a>

                <?php endif; ?>
            <?php endforeach; ?>
        </span>

        <?php if (isset($this->next)): ?>
            <a prop="pagin" class="btn btn-primary" href="<?php echo $this->url(array('page' => $this->next), 'comments'); ?>">
                <i class="fa fa-caret-square-o-right"></i>
            </a>
        <?php endif; ?>

        <?php if (isset($this->next)): ?>
            <a prop="pagin" class="btn btn-primary" href="<?php echo $this->url(array('page' => $this->last), 'comments'); ?>">
                <i class="fa fa-caret-square-o-right"></i>
                <i class="fa fa-caret-square-o-right"></i>
            </a>
        <?php endif; ?>

    </div>
<?php endif; ?>


