
<!DOCTYPE html>

<html>
    <head>
        <?php echo ''; ?>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <?php $this->headLink()->prependStylesheet($this->baseUrl('font-awesome-4.3.0/css/font-awesome.min.css', 'screen')); ?>
        <?php $this->headLink()->prependStylesheet($this->baseUrl('bootstrap-3.2.0-dist/css/bootstrap.min.css', 'screen')); ?>

        <?php echo $this->headLink() ?>
        <?php $this->headScript()->appendFile($this->baseUrl('jquery/jquery-1.11.js')); ?>
        <?php $this->headScript()->appendFile($this->baseUrl('bootstrap-3.2.0-dist/js/bootstrap.min.js')); ?>
        <?php echo $this->headScript() ?>
        <style type="text/css">
            body {

            }
            .appended {
                width: 100%;
                text-align: left;
                padding: 5px;
                white-space: normal;
                font-size: 12px;
                border-radius: 3px;
                border: 0.25em solid #ccccff;
            }

            .pagin {
                margin-right: 10px;
            }

            #pagination {
                margin-bottom: 50px;
            }

        </style>


    </head>
    <body>
        <div class="container-fluid">

            <div class="row">
                <div class="col-sm-4 col-sm-offset-4 text-center">
                    <h3>Komentarze</h3>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12" id="hook">

                </div>
            </div>

            <div class="row">
                <div class="col-sm-12 text-center" id="pagination">

                </div>
            </div>

        </div>

        <?php $urlIndex = $this->url(array(), 'comments-ajax-get'); ?>

        <script>


            $(document).ready(function () {

                var result = null;

                $.ajax({
                    url: '<?php echo $urlIndex; ?>',
                    type: "post",
                    data: '<?php echo $this->articleId; ?>',
                    success: function (res) {
                        getAllComments(res);
                    },
                    error: function (res) {
                        result = res;
                    }
                });


                $(document).on('click', '.pagin', function (e) {
                    e.preventDefault();

                    var data = JSON.stringify(['<?php echo $this->articleId; ?>', $(this).text()]);
                    console.log('DATA: ' + data);
                    $.ajax({
                        url: '<?php echo $urlIndex; ?>',
                        type: "post",
                        data: data,
                        success: function (res) {
                            getAllComments(res);

                        },
                        error: function (res) {
                            result = res;
                        }
                    });


                    //window.location.reload();

                });


            });

            function getAllComments(res)
            {
                //console.log(res);
                var parsed = JSON.parse(res);
                $('#hook').html('');
                var query = parsed.query;
                var commentsPerPage = parsed.commentsPerPage;
                var currentPage = parseInt(parsed.page);

                if (parsed.total.count > 0) {

                    var buttonsNumber = Math.round(parsed.total.count / commentsPerPage);
//                    console.log(parsed.total.count);
//                    console.log(commentsPerPage);
//                    console.log(buttonsNumber);

                    var counter = (commentsPerPage < parsed.total.count) ? commentsPerPage : parsed.total.count;
                    //console.log('counter= ' + counter);

                    for (var i = 0; i < counter; i++) {

                        if (!query[i]) {
                            break;
                        }

                        var date = new Date(parseInt(query[i].date_created, 10) * 1000);

                        var row = '<hr><div class="row"><div class="col-sm-12">';
                        row += '<p>Autor: ' + query[i].customer_username + ', dnia: ';
                        row += '<span>' + date.toLocaleString() + '</span></p>';
                        row += '<div class="form-group"><div class="well">' +
                                '<input class="form-control" type="text" value="' + query[i].title + '" style="margin-bottom:10px;" readonly />';
                        var textarea = '<textarea class="form-control" rows="5" readonly="readonly">' + query[i].content + '</textarea>';
                        row += textarea + '</div></div></div></div>';
                        $('#hook').append(row);
                        $('input, textarea').addClass('appended');

                    }

                    var visibleButtonsNumber = 5;

                    $('#pagination').html('');

                    if (buttonsNumber <= visibleButtonsNumber) {
                        for (var i = 0; i < buttonsNumber; i++) {

                            var buttonNumber = i + 1;
                            var buttonClass = (buttonNumber === currentPage) ? 'btn btn-default pagin' : 'btn btn-info pagin';
                            var button = '<a class="' + buttonClass + '" href="#">' + buttonNumber + '</a>';
                            $('#pagination').append(button);

                        }
                    } else {
                        
                        var start = currentPage - 2;
                        var stop = currentPage + 2;
                        
                        if(start < 1){
                            start = 1;
                        }
                        
                        if(stop > buttonsNumber){
                            stop = buttonsNumber;
                        }
                        
                        if(start > 1){
                            $('#pagination').append('<a class="btn btn-info pagin" href="#">1</a><a class="btn pagin" href="javascript:void(0);"> ... </a>');
                        }
                        
                        for(var i = start; i <= stop; i++){
                            var buttonClass = (i === currentPage) ? 'btn btn-default pagin' : 'btn btn-info pagin';
                            var button = '<a class="' + buttonClass + '" href="#">' + i + '</a>';
                            $('#pagination').append(button);
                        }
                        
                        if(stop < buttonsNumber){
                            $('#pagination').append('<a class="btn pagin" href="javascript:void(0);"> ... </a><a class="btn btn-info pagin" href="#">' + buttonsNumber + '</a>');
                        }
                        
                    }


                } else {
                    $('#hook').append('<h2 class="text-center">Brak komentarzy.</h2>');
                }
            }
            
            

        </script>
    </body>
</html>
