
<?php
$config = Zend_Registry::getInstance()->get('adminConfig');
$baseUrl = $config->url;
?>

<script>

    tinymce.init({
        selector: "textarea#tiny",
        relative_urls: false,
        remove_script_host: false,
        document_base_url : "<?php echo $baseUrl; ?>",
        convert_urls : true, 
        theme: "modern",
        language: "pl",
        width: null,
        height: 600,
        subfolder: "",
        plugins: [
            "advlist autolink link image lists charmap print preview hr anchor pagebreak",
            "searchreplace wordcount visualblocks visualchars code insertdatetime media nonbreaking",
            "table contextmenu directionality emoticons paste textcolor browseruploader"
        ],
        image_advtab: true,
        toolbar: "undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | styleselect forecolor backcolor | link unlink anchor | media | print preview code",
    });



</script>


</script>