<?php
$params = Zend_Controller_Front::getInstance()->getRequest()->getParams();
?>

<div class="container-fluid">



    <h3>Artykuł edycja</h3>

    <div class="row">

        <div class="col-sm-12">
            <?php echo $this->form; ?>
            <a href="<?php
            echo $this->url(array(
                'page' => isset($params['page']) ? $params['page'] : 1,
                'category-sort' => isset($params['category-sort']) ? $params['category-sort'] : 0,
                'name-sort' => isset($params['name-sort']) ? $params['name-sort'] : ''
                    ), 'articles');
            ?>" class="btn btn-default">Anuluj</a>
        </div>

    </div>

</div>

<script>

            var imagename = '<?php echo $this->photoName; ?>';
            $(document).ready(function () {

                $(document).on('click' , '#save-all', function () {
                    //alert('ok');
                    var name = $('iframe[id=image-process-iframe]').contents().find('#php-source').attr('src');
                    //console.log(name);
                    $('#image-input').attr('value', name);
                });

            });

        </script>
