


<div class="row">

    <div class="col-sm-2" style="margin-top: 10px;">
        <img src="<?php echo $this->baseUrl('files/app/cw_ico.png'); ?>" alt="CloutWork-icon" title="Home" width="100" />
    </div>

    <div class="col-sm-4 col-sm-offset-0">

        <?php if (isset($this->messages) && !empty($this->messages)): ?>
            <?php echo $this->messageBox($this->messages); ?>
        <?php endif; ?>

    </div>


    <div class="col-sm-3 col-sm-offset-1">

        <?php if (isset($this->identity) && !empty($this->identity)): ?>
            <div class="logged-info">
                <p><?php echo 'Witaj, ' . $this->identity . '.'; ?></p>
            </div>
        <?php endif; ?>

    </div>

    <div class="col-sm-2 logout-btn">

        <?php if (isset($this->identity) && !empty($this->identity)): ?>
            <a class="btn btn-danger" href="<?php echo $this->url(array(), 'logout'); ?>" >Wyloguj</a>
        <?php endif; ?>

    </div>

</div>


<?php //echo $this->menu()->writeMenu(); ?>



