<?php
$counter = 0;
//desc($this->articles);
?>

<div class="row">
    <div class="col-sm-12">
        <?php //echo $this->breadCrumbs($this->bc); ?>
    </div>

</div>


<div class="row">

    <div class="col-sm-8 col-sm-offset-2">
        <?php echo $this->bootsSliderArticles(); ?>
    </div>

</div><hr>

<?php if(count($this->articles) > 0): ?>

<div class="row">


    <div class="col-sm-6">
        <h3 class="shadowed">Najnowsze w kategorii <?php echo $this->categoryName; ?>:</h3> 
        <ul class="media-list">

            <?php while ($art = each($this->articles)): ?>

                <li class="media">
                    
                    <?php if (!empty($art['value']['photo'])): ?>
                        <a class="pull-left" href="<?php echo $this->articleUrl($art); ?>">
                            <img class="media-object" src="<?php echo $this->imageSrc($art['value']['photo']); ?>" width="100" />
                        </a>
                    <?php endif; ?>
                    <div class="media-body">
                        <a href="<?php echo $this->articleUrl($art); ?>">
                            <h4 class="media-heading">
                                <?php
                                echo strlen($art['value']['title']) > 50 ? substr($art['value']['title'], 0, 50) . ' ...' : $art['value']['title'];
                                ?>
                            </h4>

                            <p>
                                <?php echo substr($art['value']['subtitle'], 0, 200) . ' ...' ?>
                            </p>
                        </a>
                    </div>
                    
                </li><hr>

            <?php endwhile; ?>
        </ul>

        <div class="pagination-index">
            <h4 class="shadowed">Zobacz wcześniejsze artykuły w tej kategorii:</h4>
            <?php echo $this->pagination; ?>
        </div>

    </div>

    <div class="col-sm-3">
        
        <h3 class="shadowed">Warto przeczytać</h3> 
        <?php reset($this->articles); ?>

        <?php while ($art = each($this->articles)): ?>

            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="<?php ?>">
                        <p>
                            <?php
                            echo strlen($art['value']['title']) > 50 ? substr($art['value']['title'], 0, 50) . ' ...' : $art['value']['title'];
                            ?>
                        </p>
                        <p>
                            <?php echo substr($art['value']['subtitle'], 0, 200) . ' ...' ?>
                        </p>

                    </a>
                </div>
            </div>


        <?php endwhile; ?>

    </div>


    <div class="col-sm-3" style="height: 100%; border-left: 1px solid #ccccff;">
        <h3 class="shadowed">Reklamy</h3> 
        <img src="" width="90%" height="500" />

    </div>



</div>

<?php else: ?>

<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <h1 class="shadowed">Brak artykułów w tej kategorii.</h1>
    </div>
</div>

<?php endif; ?>

