
<?php //desc($this->errors);  ?>
<?php if (isset($this->errors) && !empty($this->errors)): ?>
    <div class="row">
        <div class="col-md-10 col-md-offset-1 form-messages">


            <?php while ($e = each($this->errors)): ?>

                <?php while ($error = each($e['value'])): ?>
                    <p><?php echo $error['value'] ?></p>
                <?php endwhile; ?>

            <?php endwhile; ?>
        </div>
    </div>

<?php endif; ?>


<div class="row">

    <div class="col-sm-4 col-sm-offset-1">
        <h2>Logowanie do panelu administracyjnego</h2>
    </div>
    
    <div class="col-sm-4 well">
        <?php echo $this->form; ?>
    </div>
    
</div>

