


<div class="row">

    <div class="col-md-2 col-md-offset-2">
        <h2>Rejestracja</h2>
    </div>
</div>

<?php //desc($this->errors); ?>
<?php if (isset($this->errors) && !empty($this->errors)): ?>
    <div class="row">
        <div class="col-md-10 col-md-offset-1 form-messages">


            <?php while ($e = each($this->errors)): ?>

                <?php while ($error = each($e['value'])): ?>
                    <p><?php echo $error['value'] ?></p>
                <?php endwhile; ?>

            <?php endwhile; ?>
        </div>
    </div>

<?php endif; ?>

<div class="row">

    <div class="col-md-4 col-md-offset-4">
        <?php echo $this->form; ?>
    </div>
</div>