
<?php $counter = 0; ?>

<div class="container-fluid">
    <h3>Dodaj artykuł powiązany</h3>

    <?php if (!empty($this->related)): ?>
        <div class="row">

            <div class="col-sm-12">

                <?php while ($rel = each($this->related)): ?>
                    <div class="relatedElem">
                        <a href="<?php echo $this->url(array(
                            'id' => $rel['value']['article_id'], 
                            'rel' => $rel['value']['related_id'],
                            'page' => $this->page,
                            'category-sort' => $this->category,
                            'name-sort' => $this->name
                                ), 'related-delete'); ?>"><i class="fa fa-times"></i></a>
                        <?php echo $rel['value']['title']; ?>
                    </div>

                <?php endwhile; ?>

            </div>

        </div>

    <?php endif; ?>

    <div class="row">

        <div class="col-sm-12">
            <?php echo $this->form; ?>
        </div>


    </div>

    <div class="row">
        <div class="col-sm-12">
            <a class="btn btn-default" href="<?php echo $this->url(array('page' => $this->page, 'category-sort' => $this->category, 'name-sort' => $this->name), 'related'); ?>">Zakończ</a>

        </div>
    </div>

</div>

<?php $url = $this->url(array(), 'get-related'); ?>

<script>


    $('#related_input').on('input', function () {

        //$('#related_output').append('<option value="0">Brak wyników.</option>');

        var data = $('#related_input').val();

        $('#related_output').find('option').remove();

        $.ajax({
            url: "<?php echo $url; ?>",
            type: "post",
            data: data,
            success: function (res) {

                var parsed = JSON.parse(res);

                for (var prop in parsed) {
                    $('#related_output').append('<option value="' + parsed[prop]['id'] + '">' + parsed[prop]['title'] + '</option>');
                }
                ;
            },
            error: function (res) {
                alert("Błąd!");
            }
        });
    });

</script>
