<?php ?>


<?php if ($this->error404): ?>

    <div class="row">
        <div class="col-sm-8 col-sm-offset-2" style="text-align: center;">
            <div class="row">
                <div class="col-sm-12">
                    <img src="<?php echo $this->baseUrl('/files/app/error404.png'); ?>" title="" alt="404" />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <h4><?php echo $this->message; ?></h4>
                </div>
            </div>


        </div>
    </div>


<?php else: ?>

    <div class="row">
        <div class="col-sm-8 col-sm-offset-2" style="text-align: center;">

            <div class="row">
                <div class="col-sm-12">
                    <img src="<?php echo $this->baseUrl('/files/app/error500.png'); ?>" title="" alt="500" />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <h4><?php echo $this->message; ?></h4>
                </div>
            </div>

        </div>
    </div>



<?php endif; ?>

