
<div class="container-fluid">
    <hr>
    <div class="row">
        <div class="col-md-4" style="border-right: 1px solid #ccccff;">
            <p>Kolumna 1</p>
        </div>
        <div class="col-md-4" style="border-right: 1px solid #ccccff;">
            <p>Kolumna 2</p>
        </div>
        <div class="col-md-4">
            <p>Polityka prywatności</p>
        </div>
    </div>
    <hr>
</div>

