<?php

$fc = Zend_Controller_Front::getInstance();
$id = $fc->getRequest()->getParam('id');
$categoryId = $fc->getRequest()->getParam('category-id');
$page = $fc->getRequest()->getParam('page');
$controller = $fc->getRequest()->getControllerName();
$action = $fc->getRequest()->getActionName();
$params = array(
    'id' => $id, 
    'category-id' => $categoryId, 
    'page' => $page,
    'c' => $controller,
    'a' => $action
);
?>


<div class="container-fluid">

    <div class="row" style="padding-top: 10px;">

        <div class="col-sm-8">

            <div class="row">

                <div class="col-sm-2">
                    <a href="<?php echo $this->url(array(), 'home'); ?>" >
                        <img src="<?php echo $this->baseUrl('files/app/cw_ico.png'); ?>" alt="CloutWork-icon" title="Home" width="100" />
                    </a>
                </div>

                <div class="col-sm-2">
                    <a href="#" >O serwisie</a>
                </div>

                <div class="col-sm-2">
                    <a href="#" >O Twórcy</a>
                </div>

                <div class="col-sm-2">
                    <a href="#" >Kontakt</a>
                </div>

            </div>

        </div>

        <div class="col-sm-2 header-info">

            <?php if (isset($this->messages) && !empty($this->messages)): ?>
                <?php echo $this->messageBox($this->messages); ?>
                <?php echo $this->modalWindow($this->messages); ?>
            <?php endif; ?>

        </div>

        <div class="col-sm-2 header-info">

            <?php if (isset($this->identity) && !empty($this->identity)): ?>
                <div class="row">
                    <div class="col-sm-6">
                        <p style="font-size: 10px; color: #666666; font-weight: bolder;">
                            <?php echo 'Witaj, ' . $this->identity . '.'; ?>
                        </p>
                    </div>

                    <div class="col-sm-6">
                        <a class="btn btn-default" href="<?php echo $this->url($params, 'logout'); ?>" >Wyloguj</a>
                    </div>

                </div>

            <?php else: ?>

                <div class="row">

                    <div class="col-sm-6">
                        <a class="btn btn-default" href="<?php echo $this->url($params, 'login'); ?>">Logowanie</a>
                    </div>

                    <div class="col-sm-6">
                        <a class="btn btn-default" href="<?php echo $this->url($params, 'register'); ?>">Rejestracja</a>
                    </div>


                </div>

            <?php endif; ?>

        </div>

    </div>

    <hr>

    <div class="row">

        <div class="col-sm-12" style="text-align: center;">

            <?php echo $this->mainMenu(); ?>

        </div>

    </div>
    <hr>
</div>






