
<!DOCTYPE html>

<html>
    <head>
        <?php echo $this->headTitle(); ?>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php $this->headLink()->prependStylesheet($this->baseUrl('font-awesome-4.3.0/css/font-awesome.min.css'), 'screen') ?>
        <?php $this->headLink(array('rel' => 'shortcut icon', 'href' => $this->baseUrl('files/app/favicon.png'), 'type' => 'image/x-icon'), 'PREPEND'); ?>
        <?php $this->headLink()->prependStylesheet($this->baseUrl('bootstrap-3.2.0-dist/css/bootstrap.min.css'), 'screen') ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl('css/mainStyle.css'), 'screen') ?>
        <?php echo $this->headLink(); ?>
        <?php $this->headScript()->appendFile($this->baseUrl('jquery/jquery-1.11.js')) ?>
        <?php $this->headLink()->prependStylesheet($this->baseUrl('jquery-ui-1.11.4/jquery-ui.css', 'screen')); ?>
        <?php echo $this->globalsJS(); ?>
        <?php $this->headScript()->appendFile($this->baseUrl('bootstrap-3.2.0-dist/js/bootstrap.min.js')) ?>
        <?php $this->headScript()->appendFile($this->baseUrl('js/mainScript.js')) ?>
        <?php $this->headScript()->appendFile($this->baseUrl('js/modal.js')) ?>

        <?php echo $this->headScript() ?>


        <!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

    </head>
    <body>

        <div class="container-fluid">
            <?php echo $this->render('header.phtml'); ?>
            <?php echo $this->layout()->content; ?>
            <?php echo $this->render('footer.phtml'); ?>
        </div>

        <?php echo $this->cookies(); ?>
    </body>
</html>
