<!DOCTYPE html>

<html>
    <head>
        <title>Upload obrazków</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php $this->headLink()->prependStylesheet($this->baseUrl('bootstrap-3.2.0-dist/css/bootstrap.min.css'), 'screen') ?>
        <?php $this->headLink()->prependStylesheet($this->baseUrl('css/mainStyle.css'), 'screen') ?>
        <?php echo $this->headLink() ?>
        <?php $this->headScript()->appendFile($this->baseUrl('jquery/jquery-1.11.js')) ?>
        <?php $this->headScript()->appendFile($this->baseUrl('bootstrap-3.2.0-dist/js/bootstrap.min.js')) ?>
        <?php $this->headScript()->appendFile($this->baseUrl('js/mainScript.js')) ?>

        <style type="text/css">

            .src {
                display: none;
                font-size: 10px;
            }

            .wrapper {
                position: relative;
                top: 0px;
                left: 0px;
                height: 200px;
                box-shadow: 1px 1px 2px #999999;
                float: left;
                overflow: auto;
                margin: 10px;
                padding: 5px;
            }

            .imgWrapper {
                position: absolute;
                top: 0;
                left: 0;
            }

            #formDel {
                position: absolute;
                left: 0;
                bottom: 0;
            }

            #hiddenSrc {
                position: absolute;
                width: 90%;
                left: 5%;
                top: 40%;
                height: 20%;
                display: none;
                z-index: 999;
                background: #ffcccc;
                text-align: center;
                box-shadow: 1px 1px 2px #999999;
                padding: 10px;
                overflow: auto;
            }
            
            #close {
                position: absolute;
                left: 95%;
                top: 5px;
                width: 5%;
                z-index: 9999;
                font-size: 15px;
                font-weight: bold;
            }

        </style>

    </head>
    <body>

        <div class="container">

            <?php if (isset($this->message)): ?>
                <div class="row">
                    <div class="col-sm-12">
                        <p>
                            <?php echo $this->message; ?>
                        </p>


                    </div>
                </div> 
            <?php endif; ?>

            <?php if (isset($this->errors)): ?>
                <?php while ($e = each($this->errors)): ?>
                    <div class="row">
                        <div class="col-sm-12">
                            <p>
                                <?php echo $e['value']; ?>
                            </p>

                        </div>
                    </div> 
                <?php endwhile; ?>
            <?php endif; ?>

            <div class="row" style="border-bottom: 1px dashed #999999; margin-bottom: 10px;">

                <div class="col-sm-12">
                    <?php echo $this->form; ?>
                </div>

            </div>

            <div class="row">

                <div id="hiddenSrc">
                    <a href="javascript:void(0)" id="close">X</a>
                    <p id="output"></p>
                </div>

                <div style="margin-bottom: 10px;">
                    <label style="margin-bottom: 10px;">Dostępne obrazki:</label>
                </div>


                <?php if (isset($this->list)): ?>

                    <?php while ($elem = each($this->list)): ?>

                        <div class="col-sm-2 panel wrapper">
                            <div class="imgWrapper">
                                <a href="#" class="donor" data-src="<?php echo $this->url . '/files/images/' . $elem['value']; ?>">
                                    <img class="thumbnail" src="<?php echo $this->url . '/files/thumbs/' . $elem['value']; ?>" />
                                </a>
                            </div>



                            <form role="form" id="formDel" method="post" action="<?php echo $this->url(array(), 'uploader-delete'); ?>">
                                <input class="form-control" type="hidden" name="delete" value="<?php echo $elem['value']; ?>" />
                                <input class="btn btn-default" type="submit" name="toDelete" value="Usuń" onclick="if (confirm('Czy na pewno usunąć?')) {
                                                    document.form.submit();
                                                } else {
                                                    return false;
                                                }
                                                ;" />

                            </form>

                        </div>
                    <?php endwhile; ?>

                <?php endif; ?>

            </div>


        </div>

        <script type="text/javascript" src="<?php echo $this->baseUrl('jquery/jquery-1.11.js'); ?>"></script>

        <script type="text/javascript">

                                    $(document).ready(function () {

                                        $('.donor').click(function () {
                                            var src = $(this).attr('data-src');
                                            $('#hiddenSrc').show(200);
                                            $('#output').text(src);
                                        });
                                        
                                        $('#close').click(function(){
                                            $('#hiddenSrc').css('display', 'none');
                                            return false;
                                        });

                                    });



        </script>

    </body>
</html>
