
<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation"  id="cookies">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-11">
                <p>
                    Aby lepiej odpowiadać na Twoje oczekiwania używamy cookies. Korzystając z serwisu wyrażasz zgodę na używanie cookie zgodnie z ustawieniami w Twojej przeglądarce.
                    Więcej informacji o polityce cookies znajdziesz <a href="">tutaj</a>
                </p>
            </div>
            <div class="col-sm-1">
                <a id="cookie-trigger" href="" class="btn btn-info">Akceptuję</a>
            </div>
        </div>
    </div>
</nav>

<script>
    $(document).ready(function () {

        //cookies
        
        if(getCookie('noinfo') != ""){
            $('#cookies').css('display', 'none');
        }

        $('#cookie-trigger').click(function (e) {
            e.preventDefault();
            document.cookie = "noinfo=noinfo;path=/";
            $('#cookies').fadeOut(1000);
        });
        
    });


    function getCookie(cname) {
        var name = cname + "=";
        var ca = document.cookie.split(';');
        for (var i = 0; i < ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ')
                c = c.substring(1);
            if (c.indexOf(name) == 0)
                return c.substring(name.length, c.length);
        }
        return "";
    }


</script>
