<?php ?>

<script>

    $(document).ready(function () {


        function ModalWindow(settings)
        {
            var css = {
                position: 'absolute',
                width: settings.width,
                'min-height': settings.height,
                top: settings.top,
                left: settings.left,
                background: '#ffffff',
                'z-index': '99999',
                'border-radius': '5px',
                overflow: 'hidden',
                padding: '10px',
                'box-shadow': '0px 0px 0px 8px rgba(0,0,0,0.3)'
            };
            var overlay = '<div class="row" id="overlay"></div>';
            var append = '<div id="modal-window"></div>';
            var row = '<div id="row" class="row" id="content"></div>';
            var col = '<div id="col" class="col-sm-12"></div>';
            var close = '<div class="row"><div class="col-sm-1 col-sm-offset-11" style="text-align:right;">' +
                    '<a id="close" class="btn btn-default">X</a>' +
                    '</div></div>';

            this.show = function ()
            {
                $('body').prepend(overlay);
                $('body').prepend(append);
                $('#modal-window').css(css);
                $('#modal-window').append(row);
                $('#row').append(col);
                $('#col').append(close);

            };

            this.close = function ()
            {
                $('#modal-window').css('display', 'none');
                $('#overlay').css('display', 'none');
            };

            this.insert = function (html) {
                $('#col').append(html);
            };

        }

        var content = '<?php echo $this->string; ?>';
        var modal;
        var html = '<div class="row"><div class="col-sm-12" style="text-align:center; padding-bottom:20px;">' + content + '</div></div>';
        modal = new ModalWindow({width: '50%', top: '30%', left: '25%', 'min-height': '40%'});
        modal.show();
        modal.insert(html);

        $('body').on('click', '#close', function (e) {
            e.preventDefault();
            modal.close();
        });


    });



</script>