
<?php
$id = $this->id;
//desc($this->articles);
$counter = 0;
?>

<div class="row">

    <div class="<?php echo $this->class; ?>">

        <div id="<?php echo 'carousel-' . $id; ?>" class="carousel slide" data-ride="carousel">
            <!-- Wskaźniki w postaci kropek -->
            <ol class="carousel-indicators">
                <?php for ($i = 0; $i < count($this->files); $i++): ?>
                    <li data-target="#<?php echo 'carousel-' . $id; ?>" 
                        data-slide-to="<?php echo $i; ?>" <?php echo ($i == 0) ? 'class="active"' : ''; ?>>

                    </li>
                <?php endfor; ?>
            </ol>

            <!-- Slajdy -->
            <div class="carousel-inner" role="listbox" style="box-shadow: 2px 2px 2px #9999ff;">

                <?php while ($art = each($this->articles)): ?>

                    <div class="<?php echo ($counter == 0) ? 'item active' : 'item'; ?>">

                        <div class="media" style="height:100px; overflow-y: hidden; margin: 10px;">

                            <?php if (!empty($art['value']['photo'])): ?>
                                <a class="pull-left" href="<?php echo $this->articleUrl($art); ?>">
                                    <img class="media-object" src="<?php echo $this->imageSrc($art['value']['photo']); ?>" width="100" />
                                </a>
                            <?php endif; ?>
                            <div class="media-body">
                                <a href="<?php echo $this->articleUrl($art); ?>">
                                    <h4 class="media-heading">
                                        <?php
                                        echo strlen($art['value']['title']) > 50 ? substr($art['value']['title'], 0, 50) . ' ...' : $art['value']['title'];
                                        ?>
                                    </h4>

                                    <p>
                                        <?php echo substr($art['value']['subtitle'], 0, 200) . ' ...' ?>
                                    </p>
                                </a>
                            </div>

                        </div>

                    </div>
                    <?php $counter++ ?>
                <?php endwhile; ?>


            </div>

            <!-- Strzałki do przewijania -->
            <a onclick="return false;" class="left carousel-control" href="#<?php echo 'carousel-' . $id; ?>" data-slide="prev" style="background: none;">
                <span class="icon-prev"></span>
            </a>
            <a onclick="return false;" class="right carousel-control" href="#<?php echo 'carousel-' . $id; ?>" data-slide="next" style="background: none;">
                <span class="icon-next"></span>
            </a>


        </div>

    </div>

</div>