
<div class="row">
    
    <div class="col-sm-12">
        <h3>Kategorie artykułów</h3>
    </div>
    
</div>

<div class="row" style="margin-bottom: 20px;">
    <div class="col-sm-1">
        <a class="btn btn-info" href="<?php echo $this->url(array(), 'categories-add'); ?>"><i class="fa fa-plus-square"></i> Dodaj kategorię</a>
    </div>
    
</div>

<?php echo $this->datatable; ?>
        



