<!DOCTYPE html>

<html>
    <head>
        <title>Mail</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <style type="text/css">
            body {
                background: #006666;
                color: #00cccc;
                margin: 0;
                padding: 20px;
            }
            
            #wrapper {
                position: relative;
                width: 50%;
                left: 25%;
                text-align: center;
                border: 1px solid whitesmoke;
                border-radius: 5px;
                padding: 10px;
            }
            
            #header {
                position: relative;
                width: 50%;
                left: 25%;
                text-align: center;
            }
            
        </style>
        
    </head>
    <body>
        <div id="header" align="center">
            <p>
                Treść maila
            </p>
        </div>
        
        <div id="wrapper" align="center">
            <p>
                <?php echo $this->content; ?>
            </p>
        </div>
    </body>
</html>
