<!DOCTYPE html>

<html>
    <head>
        <title>Mail</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <style type="text/css">
            body {
                background: #ccccff;
                color: #cc0000;
                margin: 0;
                padding: 20px;
            }

            #wrapper {
                position: relative;
                width: 90%;
                left: 5%;
                text-align: center;
                border: 2px solid #cc0000;
                border-radius: 5px;
                padding: 10px;
            }

            #header {
                position: relative;
                width: 50%;
                left: 25%;
                text-align: center;
            }

            pre {
                white-space: pre-wrap;       /* css-3 */
                white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
                white-space: -pre-wrap;      /* Opera 4-6 */
                white-space: -o-pre-wrap;    /* Opera 7 */
                word-wrap: break-word;       /* Internet Explorer 5.5+ */
                overflow: auto;
                width: 100%;
            }

        </style>

    </head>
    <body>
        <div id="header" align="center">
            <p>
                Treść maila
            </p>
        </div>

        <div id="wrapper" align="center">
            <pre>
                <?php print_r($this->content); ?>
            </pre>
        </div>
    </body>
</html>
